apiVersion: v1
kind: Service
metadata:
  name:  mtech-rtp-service
  namespace: mtech
spec:
  type: NodePort
  selector:
    app: mtech-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000